#  C:\Users\raysm\vscode\simple_games\sudoku-master\sudoku.properties  20250428_104633
play_control.win_height=388
play_control.win_width=488
play_control.win_x=234
play_control.win_y=234
run_control.Display_time=0.0
run_control.PuzzleSym=c
run_control.UsePuzzle=False
run_control.bSize=3
run_control.label_1=Puzzle Dimensions
run_control.label_2=
run_control.label_3=Puzzle Size
run_control.label_4=
run_control.label_5=Running Control
run_control.label_6=Display Time
run_control.makePuzzle=False
run_control.nCol=9
run_control.nFirst=5
run_control.nRow=9
run_control.nSubCol=3
run_control.nSubRow=3
run_control._redo_no=0
run_control._restore_no=0
run_control.run_after_load=False
run_control.sSize=2
run_control._save_no=0
run_control.traceList=
run_control.update_time=10.0
run_control.xPer=False
traceFlag.any=False
traceFlag.controls=1
traceFlag.decpl=False
traceFlag.depth=False
traceFlag.display_board=False
traceFlag.empty=False
traceFlag.getnextchoice=False
traceFlag.list_props=False
traceFlag.no_ts=False
traceFlag.prop_change=False
traceFlag.puzzle_load=False
traceFlag.resource=False
traceFlag.setcell=False
traceFlag.setplydata=False
traceFlag.show_data=False
traceFlag.solve=False
traceFlag.solvechoice=False
traceFlag.stdouthasts=False
traceFlag.sudokuply=False
traceFlag.trace_flags=1
traceFlag.trace_move=False
traceFlag.track_vals=False
